services:
  postgres:
    image: postgres:16
    container_name: jobtracker-postgres
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
    ports:
      - "5433:5432"
    volumes:
      - jobtracker_pgdata:/var/lib/postgresql/data

volumes:
  jobtracker_pgdata:
